version: "3.8"
services:
  # mongo_db:
  #   container_name: muse_connect_db
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo_db:/data/db

  server:
    build: ./server
    container_name: muse_connect_server
    ports:
      - '4000:4000'
    # depends_on:
    #   - mongo_db
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./frontend
    container_name: muse_connect_client
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/muse:/app
      - /app/node_modules

# volumes:
#   mongo_db: {}